apiVersion: v1
kind: Template
metadata:
  annotations:
    iconClass: fa fa-docker
    description: Template permettant de créer une image Docker depuis un dépôt Git
    tags: docker
    version: 1.0.0
    openshift.io/display-name: Docker
  name: docker
parameters:
- displayName: Nom de l'image
  description: Le nom de l'image Docker à builder
  name: APPLICATION_NAME
  required: true
- displayName: URL du dépôt Git
  description: L'emplacement du dépôt Git, dans lequel se trouve le Dockerfile
  name: GIT_URL
  required: true
- displayName: Répertoire
  description: Répertoire du dépôt Git dans lequel se trouve le Dockerfile
  name: CONTEXT_DIR
  required: false
labels:
  template: docker
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    namespace: osllecomtech
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        uri: ${GIT_URL}
      type: Git
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange

